from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from apps.projects.models import Project, ProgrammeUnit, ProjectReportingStatus, ReportingCycle
from apps.monitoring.models import OutputVerification


class ReportingHomeView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'reporting/home.html')


class ProgressReportView(LoginRequiredMixin, View):
    def get(self, request):
        co = getattr(request, 'active_country_office', None)
        year = int(request.GET.get('year', 2026))
        quarter = request.GET.get('quarter', 'Q1')
        projects = Project.objects.filter(country_office=co).select_related('programme_unit') if co else Project.objects.none()
        cycle = ReportingCycle.objects.filter(country_office=co, year=year, quarter=quarter, cycle_type='progress').first()
        statuses = ProjectReportingStatus.objects.filter(cycle=cycle).select_related('project') if cycle else []
        return render(request, 'reporting/progress.html', {
            'projects': projects, 'cycle': cycle, 'statuses': statuses,
            'year': year, 'quarter': quarter,
        })


class OutputVerificationReportView(LoginRequiredMixin, View):
    def get(self, request):
        co = getattr(request, 'active_country_office', None)
        verifications = OutputVerification.objects.filter(project__country_office=co).select_related('project', 'cycle') if co else []
        return render(request, 'reporting/verification.html', {'verifications': verifications})


class IndicatorAchievementReportView(LoginRequiredMixin, View):
    def get(self, request):
        co = getattr(request, 'active_country_office', None)
        from apps.projects.models import CPDIndicator
        indicators = CPDIndicator.objects.filter(outcome__framework__country_office=co).prefetch_related('achievements') if co else CPDIndicator.objects.none()
        return render(request, 'reporting/indicators.html', {'indicators': indicators})


class DonorReportView(LoginRequiredMixin, View):
    def get(self, request):
        co = getattr(request, 'active_country_office', None)
        from apps.projects.models import DonorReportingTimeline
        timelines = DonorReportingTimeline.objects.filter(country_office=co).select_related('project') if co else []
        return render(request, 'reporting/donor.html', {'timelines': timelines})


class ExportReportView(LoginRequiredMixin, View):
    def get(self, request, report_type):
        import csv
        from django.http import HttpResponse
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f'attachment; filename="{report_type}_report.csv"'
        writer = csv.writer(response)
        writer.writerow(['Report Type', report_type, 'Generated by Dodo'])
        return response
